# Generated by Django 3.0.8 on 2020-07-06 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200706_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanfollowing',
            name='profile_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_from_set', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='fanfollowing',
            name='profile_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_to_set', to='account.Profile'),
        ),
    ]
