version: "3"

services:
  web:
    build: .
    ports:
      - 9000:9000
    volumes:
      - .:/application
    #command: sh -c "python manage.py runserver 0.0.0.0:9000"
    command: sh -c "python manage.py runserver_plus 0.0.0.0:9000 --cert-file cert.file"


    