# Generated by Django 3.0.8 on 2020-07-06 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='target_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(app_label__in=['account', 'actions', 'images']), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_objects', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='action',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
