# Generated by Django 3.0.8 on 2020-07-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20200706_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='verb',
            field=models.CharField(choices=[('is following', 'is following'), ('bookmarked image', 'bookmarked image'), ('liked', 'liked'), ('has joined the platform', 'has joined the platform')], max_length=150),
        ),
    ]
